name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - dev  # feature -> dev 로 PR을 보낼 때 작동

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # pnpm 설치 및 설정
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install
        working-directory: ./website

      - name: Build
        run: pnpm build
        working-directory: ./website
        # package.json에 정의된 "tsc -b && vite build"가 실행됩니다.`

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDGOC_CUK_WEBSITE }}' # CLI가 생성한 시크릿 이름 확인 필요
          projectId: gdgoc-cuk-website # init 할 때 선택한 프로젝트 ID로 변경
          channelId: live # PR 미리보기는 자동 채널을 사용하지만 명시 가능
          entryPoint: ./website